### ISSUE TITLE
AttributeError: 'module' object has no attribute 'conv'

### ISSUE THREAD

**Issue by yoyo1989** [nyusngroup/SESNspectraLib#2]
I still has an error:

```
[1] import Ic_conv_Icbl_MCMC as Ic_conv_Icbl

[2] Ic_conv_Icbl.conv('10qts_20100815_Lick_3-m_v1-z.flm-flat.sav', 'meanspecIc_0.sav')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-137-cf16eb268141> in <module>()
----> 1 Ic_conv_Icbl.conv('10qts_20100815_Lick_3-m_v1-z.flm-flat.sav', 'meanspecIc_0.sav')

AttributeError: 'module' object has no attribute 'conv'
```

I can run the following:

```
[3] %run /Users/yuqianliu/github_rep/SESNspectraLib/Ic_conv_Icbl_MCMC.py
Mean acceptance fraction: 0.560
16th, 50th, 84th percentiles of marginalized distributionof model parameters
[ 11.03473214  11.31697052  11.57283873] for v/1000 in km/s
[ 4.2355698   4.54219278  4.86659571] for sigma/1000 in km/s
[ 1.31041678  1.40845969  1.50139907] for amplitude
[ 0.54435987  2.45664605  6.51081607] for wave-range in angstrom
minimization took 47.1844210625 seconds
```

**Comment by fedhere** [comment]
not for me! how are you rinning it? on the console or running a code? if it
is a code just send it to me. I have no pvoblems accessing the conv function

_fbianco@octomore_: 00:45:57:_~/science/Dropbox/SESNspectraLib_$ipython
-pylab

WARNING: `-pylab` flag has been deprecated.

```
Use `--matplotlib <backend>` and import pylab manually.
```

Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58)

Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.

?         -> Introduction and overview of IPython's features.

%quickref -> Quick reference.

help      -> Python's own help system.

object?   -> Details about 'object', use 'object??' for extra details.

Using matplotlib backend: MacOSX

In [_1_]: import Ic_conv_Icbl_MCMC as Ic_conv_Icbl

In [_2_]: Ic_conv_Icbl.conv('10qts_20100815_Lick_3-m_v1-z.flm-flat.sav',
'meanspecIc_0.sav')

Mean acceptance fraction: 0.482

[  1.14233564  11.28010267   0.13575217   1.47206235]

[ 1.07997775  1.15911308  1.24827267]

[ 11.06428127  11.33464453  11.57015497]

[ 0.08001291  0.1438657   0.21158337]

[ 1.39115553  1.49637079  1.58771267]

also

_fbianco@octomore_: 00:44:34:_~/science/Dropbox/SESNspectraLib_$ipython
-pylab

WARNING: `-pylab` flag has been deprecated.

```
Use `--matplotlib <backend>` and import pylab manually.
```

Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58)

Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.

?         -> Introduction and overview of IPython's features.

%quickref -> Quick reference.

help      -> Python's own help system.

object?   -> Details about 'object', use 'object??' for extra details.

Using matplotlib backend: MacOSX

In [_1_]: from Ic_conv_Icbl_MCMC import conv

In [_2_]: conv('10qts_20100815_Lick_3-m_v1-z.flm-flat.sav',
'meanspecIc_0.sav')

Mean acceptance fraction: 0.507

[  1.14840129  11.31480125   0.13616977   1.49151557]

[ 1.06429192  1.15054724  1.2400782 ]

[ 11.07420421  11.32485928  11.59135357]

[ 0.08639289  0.14751213  0.20644952]

[ 1.38054796  1.47734153  1.5939386 ]

so I cannot reproduce your error

On Fri, Jul 1, 2016 at 11:51 PM, Yuqian Liu notifications@github.com
wrote:

> I still has an error:
> 
> [1] import Ic_conv_Icbl_MCMC as Ic_conv_Icbl
> 
> ## [2] Ic_conv_Icbl.conv('10qts_20100815_Lick_3-m_v1-z.flm-flat.sav', 'meanspecIc_0.sav')
> 
> AttributeError                            Traceback (most recent call last)
> <ipython-input-137-cf16eb268141> in <module>()
> ----> 1 Ic_conv_Icbl.conv('10qts_20100815_Lick_3-m_v1-z.flm-flat.sav', 'meanspecIc_0.sav')
> 
> AttributeError: 'module' object has no attribute 'conv'
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nyusngroup/SESNspectraLib/issues/2, or mute the
> thread
> https://github.com/notifications/unsubscribe/ABnkhkwF9n9N3wpDLyGWMrXtBgfDLvzzks5qReBYgaJpZM4JDl_1
> .

## 

---

dr. federica bianco
NYU-Center for Cosmology & Particle Physics
NYU-Center for Urban Science & Progress
New York, NY

http://cosmo.nyu.edu/~fb55/

---

  //\
 //||\     Please consider the environment before printing this e-mail

email checking schedule:
9-5 on the hour. otherwise sporadically.

**Comment by yoyo1989** [comment]
I run it on Canopy console. Now it works. I just closed Canopy and restart a few times...
