### ISSUE TITLE
sometimes encounter UserWarning, FutureWarning, RuntimeWarning

### ISSUE THREAD

**Issue by yoyo1989** [nyusngroup/SESNspectraLib#3]
When I run the following code

```
import Ic_conv_Icbl_MCMC as Ic_conv_Icbl
Ic_conv_Icbl.conv('10qts_20100815_Lick_3-m_v1-z.flm-flat.sav', 'meanspecIc_0.sav')

```

Sometimes there are Warnings:

```
/Users/yuqianliu/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/axes/_axes.py:476: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
/Users/yuqianliu/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py:2264: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  different = bool(ours != theirs)
```

or

```
/Users/yuqianliu/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/pyplot.py:424: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
```

For the RuntimeWarning, I think I did close plots in the code. I don't know if I need to worry about these warnings.

**Comment by fedhere** [comment]
i think they are ok, but you waid "sometimes". it would be less concerning
if you got them all the time. can you clarify?

On Sat, Jul 2, 2016 at 8:08 AM, Yuqian Liu notifications@github.com wrote:

> When I run the following code
> 
> import Ic_conv_Icbl_MCMC as Ic_conv_Icbl
> Ic_conv_Icbl.conv('10qts_20100815_Lick_3-m_v1-z.flm-flat.sav', 'meanspecIc_0.sav')
> 
> Sometimes there are Warnings:
> 
> /Users/yuqianliu/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/axes/_axes.py:476: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
>   warnings.warn("No labelled objects found. "
> /Users/yuqianliu/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py:2264: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
>   different = bool(ours != theirs)
> 
> or
> 
> /Users/yuqianliu/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/pyplot.py:424: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
>   max_open_warning, RuntimeWarning)
> 
> For the RuntimeWarning, I think I did close plots in the code. I don't
> know if I need to worry about these warnings.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nyusngroup/SESNspectraLib/issues/3, or mute the
> thread
> https://github.com/notifications/unsubscribe/ABnkhjx7Kh4teIAI1HQ0yBwSspWHgK5Cks5qRlTMgaJpZM4JDqaZ
> .

## 

---

dr. federica bianco
NYU-Center for Cosmology & Particle Physics
NYU-Center for Urban Science & Progress
New York, NY

http://cosmo.nyu.edu/~fb55/

---

  //\
 //||\     Please consider the environment before printing this e-mail

email checking schedule:
9-5 on the hour. otherwise sporadically.

**Comment by fedhere** [comment]
i separated the pdf outputs,  this avoids importing the pdfpages backend  and will help with some warnings. the figures should now be closed properly. I added the assignment of the figure when you open a new figure (fig = pl.figure() instead of just pl.figure()) which avoids popping up the figure when running on the command line or console)
