### ISSUE TITLE
SNspecFFTsmooth.pro: language used is still for old paper version

### ISSUE THREAD

**Issue by mmoJazz** [nyusngroup/SESNspectraLib#32]
The language for the variables in the code reflect the submitted/old version of the appendix, but we had major changes in the wording for the final version of the appendix. Please make sure that the published version of the code reflects the _final_ version of the appendix. 
- example 1:
  line 62: intercept=mean(abs(f_bin_ft(num_lower :num_upper)))
  this is for the old version where you talked about the "intercept" of the "straight line fit" - which we are no longer doing the appendix. So I would suggest (but check if I'm right) that you replace "intercept" with "mag_average" or something like that. "intercept" would completely confuse the reader/user and since this code claims to do things for the first time, I think it's prudent to clearly annotate the code so people can understand it.
- example 2:
  in the next line you have
    f_bin_ft_line=(f_bin_ft_line+1.0) \* intercept ; a straight line along x axis
  but  f_bin_ft_line is actually never used! Please remove this line if it's not necessary (again this goes back with our old version of the paper where we talked about "a straight line fit"  - which was never a fit and not a straight line - as you remember we didn't realized initially that the powerspectrum of the noise , displayed in _log space_ will not be a constant !!
- example 3:
  I'm not sure how you get the guess values for the parameters of the powerlaw fit: you first do a linear fit??? Please explain!!!
- example 4: 
  What do you mean with :
   ; if there is still no intersection after trying a few initial guess values, then return, and let
    ; the user try a few more intial guess values
  -> specifically: "let the user try a few more initial guess values"? THe code just returns back to command line, so "let the user try a few more initial guess values" is not actually the case since there is no interactive way to input guess values but just what is hard-coded in the code (namely 3 attempts  with different guess values). SO wouldn't it be more correct to stop after "then return" - and basically the attempt has failed?

PLEASE check the rest of your code for such similar things!

**Comment by yoyo1989** [comment]
example1:
You are right. I've changed the 'intercept' to mag_average.

example2:
You are right. The 'f_bin_ft_line' is not used and I've deleted it.

example3:
the initial guess for a power law fit is to fit log(data) to a linear model, as shown in the powerlaw_fit.pro:
https://people.ok.ubc.ca/erosolo/idl/lib/powerlaw_fit.pro
Since I found that the default initial guess in the above code sometimes gives unreasonable power law fit, e.g., upside down power law fit, I try to change the initial guess to get a reasonable power law fit. The initial guess for parameters are necessary since the algorithm will start from the initial guess to explore the parameter space. If the initial guess is not good, the exploration may be restricted in a small region and the final parameter values may get stuck on local optimum, thus the final power law fit may be unreasonable.

example4:
Yes, if the provide three initial guesses all failed (it'll be very rare though), the code just returns back to command line. What I mean is that the user can modify the code to try a few more initial guess values. I presume people will modify our code to meet their needs, but not treat our code as a black box...
I just changed the comment to make it more clear.

**Comment by mmoJazz** [comment]
Great thanks for the detailed explanation and changes! I modified your comments for example 4 somewhat in the code, to make it even clearer to the user. I think we can close this issue (but see my re-opening of the other issue about SNspecFFTsmooth.pro)
