### ISSUE TITLE
from __future__ import print_function

### ISSUE THREAD

**Issue by yoyo1989** [nyusngroup/SESNspectraLib#8]
I've noticed that the latest version of Ic_conv_Icbl_MCMC.py contains the following line:
`from __future__ import print_function`

I didn't see **print_function** is used in the code. I was wondering if I can remove this line.

**Comment by fedhere** [comment]
that line overwrites the print statement to a print fnction, which requires
the argument in parenthesis. this makes the code forward compatible with
the print statement syntax in python 3

On Sun, Jul 3, 2016 at 4:13 PM, Yuqian Liu notifications@github.com wrote:

> I've noticed that the latest version of Ic_conv_Icbl_MCMC.py contains the
> following line:
> from **future** import print_function
> 
> I didn't see _print_function_ is used in the code. I was wondering if I
> can remove this line.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nyusngroup/SESNspectraLib/issues/8, or mute the
> thread
> https://github.com/notifications/unsubscribe/ABnkhgpw2Qgc9WrPqgyov_ud6wYXorKLks5qSBfRgaJpZM4JD8Jj
> .

## 

---

dr. federica bianco
NYU-Center for Cosmology & Particle Physics
NYU-Center for Urban Science & Progress
New York, NY

http://cosmo.nyu.edu/~fb55/

---

  //\
 //||\     Please consider the environment before printing this e-mail

email checking schedule:
9-5 on the hour. otherwise sporadically.

**Comment by fedhere** [comment]
http://stackoverflow.com/questions/388069/python-graceful-future-feature-future-import

On Tue, Jul 5, 2016 at 1:32 AM, federica fb55@nyu.edu wrote:

> that line overwrites the print statement to a print fnction, which
> requires the argument in parenthesis. this makes the code forward
> compatible with the print statement syntax in python 3
> 
> On Sun, Jul 3, 2016 at 4:13 PM, Yuqian Liu notifications@github.com
> wrote:
> 
> > I've noticed that the latest version of Ic_conv_Icbl_MCMC.py contains the
> > following line:
> > from **future** import print_function
> > 
> > I didn't see _print_function_ is used in the code. I was wondering if I
> > can remove this line.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/nyusngroup/SESNspectraLib/issues/8, or mute the
> > thread
> > https://github.com/notifications/unsubscribe/ABnkhgpw2Qgc9WrPqgyov_ud6wYXorKLks5qSBfRgaJpZM4JD8Jj
> > .
> 
> ## 
> 
> ---
> 
> dr. federica bianco
> NYU-Center for Cosmology & Particle Physics
> NYU-Center for Urban Science & Progress
> New York, NY
> 
> http://cosmo.nyu.edu/~fb55/
> 
> ---
> 
>   //\
>  //||\     Please consider the environment before printing this e-mail
> 
> email checking schedule:
> 9-5 on the hour. otherwise sporadically.

## 

---

dr. federica bianco
NYU-Center for Cosmology & Particle Physics
NYU-Center for Urban Science & Progress
New York, NY

http://cosmo.nyu.edu/~fb55/

---

  //\
 //||\     Please consider the environment before printing this e-mail

email checking schedule:
9-5 on the hour. otherwise sporadically.

**Comment by yoyo1989** [comment]
Thanks!
